media: media
content:
  - name: jobs
    label: Jobs
    type: collection
    path: content/jobs
    fields:
      - name: code
        type: string
      - name: title
        type: string
      - name: summary
        type: string
      - name: salary
        type: string
      - name: location
        type: string
      - name: description
        type: rich-text
      - name: requirements
        type: rich-text
      - name: benefits
        type: rich-text